---

# Inspired by wonderful blog post of locking down fresh box.
#
#  https://ryaneschinger.com/blog/securing-a-server-with-ansible/

- name: Install opsec packages
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: install-packages-opsec
    apply:
      tags:
        - install-packages-opsec
  tags:
    - install-packages-opsec
    - zoidy_troglodyte-default

- name: Disable unused packages
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: disable-unused-services
    apply:
      tags:
        - disable-unused-services
  tags:
    - disable-unused-services
    - zoidy_troglodyte-default

# ***

- name: Configure firewall
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: setup-ufw-firewall
    apply:
      tags:
        - setup-ufw-firewall
  tags:
    - setup-ufw-firewall
    - zoidy_troglodyte-default

- name: Configure logwatch
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: setup-log-watch
    apply:
      tags:
        - setup-log-watch
  tags:
    - setup-log-watch
    - zoidy_troglodyte-default
# FIXME/2019-04-16: Emails are wired (to personal Gmail); now setup logwatch.
  when: False

- name: Disable Password Auth & Root SSH Login
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: ssh-harden-config
    apply:
      tags:
        - ssh-harden-config
  tags:
    - ssh-harden-config
    - zoidy_troglodyte-default

# ***

- name: Install Latest gocryptfs release
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: cli-gocryptfs
    apply:
      tags:
        - cli-gocryptfs
  tags: cli-gocryptfs

- name: Let anyuser elevate ‘tomb’
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: update-sudoers-tomb
    apply:
      tags:
        - update-sudoers-tomb
  tags: update-sudoers-tomb

