# vim:tw=0:ts=2:sw=2:et:norl:ft=yaml.ansible
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/landonb/zoidy_troglodyte#🧔
# License: GPLv3
---

# THANX/2018-12-16: Some task(s) below inspired by wonderful blog
# post about locking down fresh Linux box.
#
#  https://ryaneschinger.com/blog/securing-a-server-with-ansible/

- name: Install opsec packages
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: install-packages-opsec
    apply: { tags: always }
  tags: install-packages-opsec

- name: Disable unused packages
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: disable-unused-services
    apply: { tags: always }
  tags: disable-unused-services

# ***

- name: Configure firewall
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: setup-ufw-firewall
    apply: { tags: always }
  tags: setup-ufw-firewall

- name: Configure logwatch
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: setup-log-watch
    apply: { tags: always }
  tags: setup-log-watch
# FIXME/2019-04-16: Emails are wired (to personal Gmail); now setup logwatch.
  when: false

- name: Disable Password Auth & Root SSH Login
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: ssh-harden-config
    apply: { tags: always }
  tags: ssh-harden-config

# ***

# Not *quite* security-related, but system-related, which makes
# this playbook the most appropriate Zoidy project to wire this.
- name: Enable zswap
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: grub-initramfs-zswap
    apply: { tags: always }
  tags: grub-initramfs-zswap

# ***

- name: Relocate ~/.sudo_as_admin_successful
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: update-sudoers-admin-flag
    apply: { tags: always }
  tags: update-sudoers-admin-flag

# ***

# OPTIN: Some of the remaining tasks are opt-in.
#
# - SAVVY: Note we use `when` to enforce opt-in,
#   and not `tags: never`, which supports site.yml
#   role tag inheritence.
#
# - DEVEL: Uncomment this debug task to get an idea
#   how ansible_run_tags is used:
#
#   - name: Display ansible_run_tags
#     debug:
#       msg: "ansible_run_tags: {{ ansible_run_tags }}"

# ****

# OPTIN/2025-11-11: We now recommend that you install
# gocryptfs from APT, because the project is stable,
# and so we don't have to maintain this GH installer.
# - (Which is to say, this task might not work; but
#    we're keeping it at the ready in case we ever
#    need to revive it.)
- name: Install Latest gocryptfs release
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: cli-gocryptfs
    apply: { tags: always }
  tags: cli-gocryptfs
  when: "'cli-gocryptfs' in ansible_run_tags"

# This task adds at least 'tomb' to /etc/sudoers.
# - OPTIN: You can also choose to add the swapff,
#   swapon, and e2label commands.
#   - See notes atop the task file for thoughts.
- name: Let any user elevate ‘tomb’
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: update-sudoers-tomb
    apply: { tags: always }
  tags: update-sudoers-tomb

# ****

# OPTIN/2023-05-05: This task sets up an over-the-top email
# alert if someone SSH's from an unlisted MAC address.
# (There's no harm enabling this, but it's something
#  for the truly anxious, so we'd rather you specify
#  it explicitly, so you know what you're getting.)
- name: Wire PAM SSH intrusion detection
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: pam-sshd-overkill
    apply: { tags: always }
  tags: pam-sshd-overkill
  when: "'pam-sshd-overkill' in ansible_run_tags"

# ****

# OPTIN: See atop task file for considerations enabling unattended-upgrades.
- name: Configure Unattended Installs
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: unattended-installs
    apply: { tags: always }
  tags: unattended-installs
  when: "'unattended-installs' in ansible_run_tags"

# ****

- name: Prevent Suspend from Login Screen
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: gdm-greeter-nosuspend
    apply: { tags: always }
  tags: gdm-greeter-nosuspend
  when: "'gdm-greeter-nosuspend' in ansible_run_tags"

# ***
