---

# Inspired by wonderful blog post of locking down fresh box.
#
#  https://ryaneschinger.com/blog/securing-a-server-with-ansible/

- name: Install opsec packages
  include_role:
    name: zoidy_troglodyte
    tasks_from: install-packages-opsec
    apply:
      tags:
        - install-packages-opsec
  tags: install-packages-opsec

- name: Install opsec packages
  include_role:
    name: zoidy_troglodyte
    tasks_from: disable-unused-services
    apply:
      tags:
        - disable-unused-services
  tags: disable-unused-services

# ***

- name: Configure firewall
  include_role:
    name: zoidy_troglodyte
    tasks_from: setup-ufw-firewall
    apply:
      tags:
        - setup-ufw-firewall
  tags: setup-ufw-firewall

- name: Configure logwatch
  include_role:
    name: zoidy_troglodyte
    tasks_from: setup-log-watch
    apply:
      tags:
        - setup-log-watch
  tags: setup-log-watch
# FIXME/2018-12-16: Figure out how to wire emails, then setup logwatch.
  when: False

- name: Disable Password Auth & Root SSH Login
  include_role:
    name: zoidy_troglodyte
    tasks_from: ssh-harden-config
    apply:
      tags:
        - ssh-harden-config
  tags: ssh-harden-config

# ***

- name: Wire PAM SSH intrusion detection
  include_role:
    name: zoidy_troglodyte
    tasks_from: pam-sshd-overkill
    apply:
      tags:
        - pam-sshd-overkill
  tags:
    - pam-sshd-overkill
    # This task is opt-in!
    - never

# ***

- name: Configure Unattended Installs
  include_role:
    name: zoidy_troglodyte
    tasks_from: unattended-installs
    apply:
      tags:
        - unattended-installs
  tags: unattended-installs

