# vim:tw=0:ts=2:sw=2:et:norl:ft=yaml.ansible
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/landonb/zoidy_troglodyte#🧔
# License: GPLv3
---

# Some task(s) inspired by wonderful blog post of locking down fresh box.
#
#  https://ryaneschinger.com/blog/securing-a-server-with-ansible/

- name: Install opsec packages
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: install-packages-opsec
    apply: { tags: always }
  tags: install-packages-opsec

- name: Disable unused packages
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: disable-unused-services
    apply: { tags: always }
  tags: disable-unused-services

# ***

- name: Configure firewall
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: setup-ufw-firewall
    apply: { tags: always }
  tags: setup-ufw-firewall

- name: Configure logwatch
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: setup-log-watch
    apply: { tags: always }
  tags: setup-log-watch
# FIXME/2019-04-16: Emails are wired (to personal Gmail); now setup logwatch.
  when: false

- name: Disable Password Auth & Root SSH Login
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: ssh-harden-config
    apply: { tags: always }
  tags: ssh-harden-config

# ***

# Not *quite* security-related, but system-related, which makes
# this playbook the most appropriate Zoidy project to wire this.
- name: Enable zswap
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: grub-initramfs-zswap
    apply: { tags: always }
  tags: grub-initramfs-zswap

# ***

- name: Relocate ~/.sudo_as_admin_successful
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: update-sudoers-admin-flag
    apply: { tags: always }
  tags: update-sudoers-admin-flag

# ***

# PROOF:
#
# - name: Display ansible_run_tags
#   debug:
#     msg: "ansible_run_tags: {{ ansible_run_tags }}"

# ISOFF/2025-11-11: Install gocryptfs from APT
# so we don't have to maintain to GH installer.
# - So this task is now opt-in.
- name: Install Latest gocryptfs release
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: cli-gocryptfs
    apply: { tags: always }
  tags: cli-gocryptfs
  # This task is opt-in. (Note we use `when` test, not `tags: never`,
  # to support site.yml role tag inheritence.)
  when: "'cli-gocryptfs' in ansible_run_tags"

- name: Let any user elevate ‘tomb’
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: update-sudoers-tomb
    apply: { tags: always }
  tags: update-sudoers-tomb

# ***

- name: Wire PAM SSH intrusion detection
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: pam-sshd-overkill
    apply: { tags: always }
  tags: pam-sshd-overkill
  # This task is opt-in. (Using `when` test, not 'never' tag, supports
  # site.yml role tag inheritence.)
  when: "'pam-sshd-overkill' in ansible_run_tags"

# ***

- name: Configure Unattended Installs
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: unattended-installs
    apply: { tags: always }
  tags: unattended-installs
  # This task is opt-in. (Note we use `when` test, not `tags: never`,
  # to support site.yml role tag inheritence.)
  when: "'unattended-installs' in ansible_run_tags"

# ***
