---

# Inspired by wonderful blog post of locking down fresh box.
#
#  https://ryaneschinger.com/blog/securing-a-server-with-ansible/

- name: Install opsec packages
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: install-packages-opsec
    apply: { tags: always }
  tags: install-packages-opsec

- name: Disable unused packages
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: disable-unused-services
    apply: { tags: always }
  tags: disable-unused-services

# ***

- name: Configure firewall
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: setup-ufw-firewall
    apply: { tags: always }
  tags: setup-ufw-firewall

- name: Configure logwatch
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: setup-log-watch
    apply: { tags: always }
  tags: setup-log-watch
# FIXME/2019-04-16: Emails are wired (to personal Gmail); now setup logwatch.
  when: False

- name: Disable Password Auth & Root SSH Login
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: ssh-harden-config
    apply: { tags: always }
  tags: ssh-harden-config

# ***

- name: Install Latest gocryptfs release
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: cli-gocryptfs
    apply: { tags: always }
  tags: cli-gocryptfs

- name: Let anyuser elevate ‘tomb’
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: update-sudoers-tomb
    apply: { tags: always }
  tags: update-sudoers-tomb

# ***

- name: Wire PAM SSH intrusion detection
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: pam-sshd-overkill
    apply: { tags: always }
  tags: pam-sshd-overkill
  # This task is opt-in. (Using `when` test, not 'never' tag, supports
  # site.yml role tag inheritence.)
  when: "'pam-sshd-overkill' in ansible_run_tags"

# ***

- name: Configure Unattended Installs
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: unattended-installs
    apply: { tags: always }
  tags: unattended-installs
  # This task is opt-in. (Using `when` test, not 'never' tag, supports
  # site.yml role tag inheritence.)
  when: "'unattended-installs' in ansible_run_tags"

