---

# (lb): Both apache2 and nginx are installed by Linux Minut 19, and they'll
# both compete for port 80, and on my machine, nginx seems to always wins.
# - We could resolve this situation in a few different ways:
#   - Ignore the problem, as it's not hurting anything (and we only needed
#     the web server when we first stood up the machine, to install the SSH
#     key, so that Anisble could run);
#   - Edit nginx and/or apache config files to choose different port numbers;
#   - Stop nginx and/or apache services, as it's not like I use either one.
# I'm opting for the last option -- disable services you do not use!

# SAVVY/2024-02-04 15:24: Use ignore-errors. If this is the first playbook
# you run (on latest Linux Mint 21.3), none of these services exists.

- name: Disable Apache2 service
  become: true
  ansible.builtin.systemd:
    name: apache2
    state: stopped
    enabled: no
  ignore_errors: true

- name: Disable nginx service
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: stopped
    enabled: no
  ignore_errors: true

# ***

- name: Disable “very secure FTP daemon” (vsftpd) service
  become: true
  ansible.builtin.systemd:
    name: vsftpd
    state: stopped
    enabled: no
  ignore_errors: true

# ***

- name: Disable rpcbind service (for serving NFS file systems)
  become: true
  ansible.builtin.systemd:
    name: rpcbind
    state: stopped
    enabled: no
  ignore_errors: true

# ***

# (lb): I love postgres, but I only use it for jerbs!
- name: Disable PostgreSQL service
  become: true
  ansible.builtin.systemd:
    name: postgresql
    state: stopped
    enabled: no
  ignore_errors: true

