---

- name: Update APT package cache
  become: true
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade APT to the latest packages
  become: true
  apt: upgrade=safe

- name: 'Install opsec packages'
  become: true
  apt: name={{ item }}
  loop:

    # pass - lightweight directory-based password manager
    - pass

    # tomb - crypto undertaker
    - tomb

    # ufw - program for managing a Netfilter firewall
    - ufw

