---

- name: Update APT package cache
  become: true
  apt: update_cache=yes cache_valid_time=3600
  tags: install-packages-opsec

- name: Upgrade APT to the latest packages
  become: true
  apt: upgrade=safe
  tags: install-packages-opsec

- name: 'Install opsec packages'
  become: true
  apt: name={{ item }}
  tags: install-packages-opsec
  loop:

    # ufw - program for managing a Netfilter firewall
    - ufw
    # fail2ban - ban hosts that cause multiple authentication errors
    - fail2ban
    # unattended-upgrades - automatic installation of security upgrades
    - unattended-upgrades
    # logwatch - log analyser with nice output written in Perl
    - logwatch

    # SSH alternative.
    # mosh - Mobile shell that supports roaming and intelligent local echo
    - mosh

