# vim:tw=0:ts=2:sw=2:et:norl:ft=yaml.ansible
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/landonb/zoidy_troglodyte#🧔
# License: GPLv3
---

- name: Update APT package cache
  become: true
  ansible.builtin.apt: update_cache=yes cache_valid_time=3600

- name: Upgrade APT to the latest packages
  become: true
  ansible.builtin.apt: upgrade=safe

- name: 'Install opsec packages'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # pass - lightweight directory-based password manager
    - pass

    # tomb - crypto undertaker
    # https://dyne.org/software/tomb
    - tomb

    # ufw - program for managing a Netfilter firewall
    - ufw

# Author used these tools circa 2019 while developing an encrypted
# thumb drive backup solution, but I haven't used these since then.
- name: 'Install development packages'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # binwalk - tool library for analyzing binary blobs and executable code
    - binwalk

    # foremost - forensic program to recover lost files
    - foremost

    # pgpdump - PGP packet visualizer
    - pgpdump

  when: zoidy_troglodyte_include_dev_packages

