---

- name: Update APT package cache
  become: true
  ansible.builtin.apt: update_cache=yes cache_valid_time=3600

- name: Upgrade APT to the latest packages
  become: true
  ansible.builtin.apt: upgrade=safe

- name: 'Install opsec packages'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # pass - lightweight directory-based password manager
    - pass

    # tomb - crypto undertaker
    - tomb

    # ufw - program for managing a Netfilter firewall
    - ufw

    # binwalk - tool library for analyzing binary blobs and executable code
    - binwalk
    # foremost - forensic program to recover lost files
    - foremost
    # pgpdump - PGP packet visualizer
    - pgpdump

