---

- name: Load tasks dispatcher for ‘zoidy_troglodyte’
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: all
  tags:
    - disable-unused-services
    - install-packages-opsec
    - setup-ufw-firewall
    - setup-log-watch
    - ssh-harden-config
    - cli-gocryptfs
    - update-sudoers-tomb

# ***

- name: Wire PAM SSH intrusion detection
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: pam-sshd-overkill
    apply: { tags: always }
  tags: pam-sshd-overkill
  # This task is opt-in. (Using `when` test, not 'never' tag, supports
  # site.yml role tag inheritence.)
  when: "'pam-sshd-overkill' in ansible_run_tags"

# ***

- name: Configure Unattended Installs
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: unattended-installs
    apply: { tags: always }
  tags: unattended-installs
  # This task is opt-in. (Using `when` test, not 'never' tag, supports
  # site.yml role tag inheritence.)
  when: "'unattended-installs' in ansible_run_tags"

