---

- name: Load tasks dispatcher for ‘zoidy_troglodyte’
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: all
  tags:
    - cli-gocryptfs
    - disable-unused-services
    - install-packages-opsec
    - pam-sshd-overkill
    - setup-log-watch
    - setup-ufw-firewall
    - ssh-harden-config
    - unattended-installs
    - update-sudoers-tomb

