# vim:tw=0:ts=2:sw=2:et:norl:ft=yaml.ansible
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/landonb/zoidy_troglodyte#🧔
# License: GPLv3
---

- name: Load tasks dispatcher for ‘zoidy_troglodyte’
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: all
  tags:
    - cli-gocryptfs
    - disable-unused-services
    - install-packages-opsec
    - pam-sshd-overkill
    - setup-log-watch
    - setup-ufw-firewall
    - ssh-harden-config
    - unattended-installs
    - update-sudoers-tomb

