---
# Main task: Load package installers, or not, based on tags.

- name: Load tasks dispatcher for ‘zoidy_troglodyte’
  include_role:
    name: zoidy_troglodyte
    tasks_from: all
  tags:
    - install-packages-opsec
    - pam-sshd-overkill
    - setup-apt-periodic
    - setup-ufw-firewall
    - setup-log-watch
    - ssh-harden-config

