---

# CAVEAT: If you use the tag of the role itself, e.g.,
#
#   ANSIBLE_DEBUG=0 ansible-playbook ~/.zoidy/site.yml -l localhost --tags zoidy_troglodyte -K
#
# Ansible will run all tasks included by include_role (or include_tasks),
# even though marked `- never`.
#
# So that "never" tasks are skipped, use the pseudo-role task:
#
#   ANSIBLE_DEBUG=0 ansible-playbook ~/.zoidy/site.yml -l localhost --tags zoidy_troglodyte-default -K

- name: Load tasks dispatcher for ‘zoidy_troglodyte’
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: all
  tags:
    - zoidy_troglodyte-default
    #
    - disable-unused-services
    - install-packages-opsec
    - setup-ufw-firewall
    - setup-log-watch
    - ssh-harden-config
    - cli-gocryptfs
    - update-sudoers-tomb

# ***

- name: Wire PAM SSH intrusion detection
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: pam-sshd-overkill
    apply:
      tags:
        - pam-sshd-overkill
  tags:
    - pam-sshd-overkill
    # This task is opt-in!
    - never

# ***

- name: Configure Unattended Installs
  ansible.builtin.include_role:
    name: zoidy_troglodyte
    tasks_from: unattended-installs
    apply:
      tags:
        - unattended-installs
  tags:
    - unattended-installs
    # This task is opt-in!
    - never

