---

- name: Ensure /root/bin exists
  become: true
  file: path=/root/bin state=directory

- name: Add Enemy IP intrusion detection email-alert script
  become: true
  template:
    src: alert-ssh-login.j2
    dest: /root/bin/alert-ssh-login
    mode: 0775

- name: Wire Enemy IP intrusion detection email-alert task to PAM sshd
  become: true
  lineinfile:
    path: /etc/pam.d/sshd
    # You could use `optional` so that user can still logon if script fails.
    # But scripts is pretty tight, so make it required.
    #   line: 'session optional pam_exec.so seteuid /root/bin/alert-ssh-login'
    line: 'session required pam_exec.so seteuid /root/bin/alert-ssh-login'
    regexp: '^session ([^ ]+) pam_exec.so seteuid /root/bin/alert-ssh-login$'
  when: zoidy_troglodyte_pam_sshd_known_ips | length > 0

- name: Disable Enemy IP intrusion detection email-alert task to PAM sshd
  become: true
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '^session ([^ ]+) pam_exec.so seteuid /root/bin/alert-ssh-login$'
    state: absent
  when: zoidy_troglodyte_pam_sshd_known_ips | length == 0

# ***

# Message-of-the-Day customization.

- name: On SSH logon, only tell user if new mail (i.e., not empty mailbox)
  become: true
  lineinfile:
    path: /etc/pam.d/sshd
    line: 'session optional pam_mail.so quiet noenv # [1]'
    # (lb): I'd swear on one machine this was 'standard', and on another,
    # it was 'quiet' already'. So use `([^ ]+)` to match either.
    regexp: '^session +optional +pam_mail.so ([^ ]+) noenv # \[1\]$'

# Display unauthorized usage warning. Really just a legal liability,
# i.e., an accused breacher would not be able to claim that they were
# not informated.
- name: Display access warning on SSH logon — use default motd
  become: true
  template:
    # ASCII artwork courtesy:
    #
    #   http://www.gotfuturama.com/Multimedia/AsciiArt/FryRunning.shtml
    src: motd.j2
    dest: /etc/motd
  when: zoidy_troglodyte_pam_sshd_motd == ''

- name: On SSH logon, hacker can’t say I didn’t tell them so! — use user motd
  become: true
  copy:
    src: "{{ zoidy_troglodyte_pam_sshd_motd }}"
    dest: /etc/motd
  when: zoidy_troglodyte_pam_sshd_motd != ''

