---

- name: Setup ufw
  become: true
  ufw: state=enabled policy=deny

- name: Allow ssh traffic
  become: true
  ufw: rule=allow port={{ zoidy_troglodyte_ssh_port }} proto=tcp

- name: Allow mosh traffic
  become: true
  ufw:
    rule: allow
    proto: udp
    port: "{{ zoidy_troglodyte_mosh_port_beg }}:{{ zoidy_troglodyte_mosh_port_end }}"

