---

- name: Setup ufw
  become: true
  ufw: state=enabled policy=deny

- name: Remove existing UFW rules
  shell: >
    ufw status numbered | \
      grep "^\[" | \
      /bin/sed -r 's/^\[(.*)\].*/\1/' | \
      sort -r -n | \
      xargs -I '{}' ufw delete {}
  become: yes

- name: Allow ssh traffic
  become: true
  ufw: rule=allow port={{ zoidy_troglodyte_ssh_port }} proto=tcp
  when: zoidy_troglodyte_ssh_restrict_macs | length == 0

# https://en.wikipedia.org/wiki/Mosh_(software)
- name: Allow mosh traffic
  become: true
  ufw:
    rule: allow
    proto: udp
    port: "{{ zoidy_troglodyte_mosh_port_beg }}:{{ zoidy_troglodyte_mosh_port_end }}"
  # 2019-03-19 00:01: Pretty sure no need to mosh. Not tonight, at least.
  when: False

# ***

- name: Clean existing INPUT rules
  shell: >
    /sbin/iptables -L INPUT --line-numbers | \
      grep ACCEPT | \
      awk '{print $1}' | \
      sort -r -n | \
      xargs -I '{}' /sbin/iptables --delete INPUT {}
  become: yes

# E.g.,
#   /sbin/iptables -A INPUT -p tcp --destination-port 22 -m mac --mac-source XX:XX:XX:XX:XX:XX -j ACCEPT
- name: Allow ssh traffic from *just my devices*
  shell: >
    /sbin/iptables \
      -A INPUT \
      -p tcp \
      --destination-port {{ zoidy_troglodyte_ssh_port }} \
      -m mac \
      --mac-source {{ item }} \
      -j ACCEPT
  become: yes
  notify: Persist iptables
  loop: "{{ zoidy_troglodyte_ssh_restrict_macs }}"
  when: zoidy_troglodyte_ssh_restrict_macs | length > 0

# ***

- name: Install packages to persist/save iptables firewall settings across boots
  become: true
  apt: name={{ item }}
  loop:
    - netfilter-persistent
    - iptables-persistent

- name: Ensure that netfilter-persistent will be enabled at boot
  become: true
  systemd:
    name: netfilter-persistent
    state: started
    enabled: yes

