# vim:tw=0:ts=2:sw=2:et:norl:ft=yaml.ansible
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/landonb/zoidy_troglodyte#🧔
# License: GPLv3
---

- name: Disallow password authentication
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present

- name: Disallow root SSH access
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart sshd

- name: Allow only this user to SSH-connect
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    line: "AllowUsers {{ ansible_env.LOGNAME }}"
    state: present
  notify: Restart sshd

- name: "Change control node's SSH remote port number — localhost:~/.ssh/config"
  delegate_to: localhost
  ansible.builtin.lineinfile:
    dest: ~/.ssh/config
    insertafter: "^Host {{ ansible_hostname }}$"
    regexp: "\tPort\\s"
    line: "\tPort {{ zoidy_troglodyte_ssh_port }}"
    state: present
  when: zoidy_troglodyte_ssh_port != 22

# HSTRY/2025-01-05: The play used to (or least sometimes would) fail after this step.
# - But this has not been observed recently.
# - And the `Restart sshd` should run at the end of the play.
#   - So I'm confused how this used to fail.
#     (Also the @managed /etc/ssh/sshd_config change used to be before
#      the @control ~/.ssh/config change, but how would that matter.)
# - In any case, for the first run on a fresh machine, you'd run, e.g.,:
#     ansible-playbook ... --tags zoidy_troglodyte -K -e "ansible_port=22"
# - And if you need to run it again, you'll rely on zoidy_troglodyte_ssh_port:
#     ansible-playbook ... --tags zoidy_troglodyte -K
- name: "Change managed node's SSH server port number — {{ ansible_hostname }}:/etc/ssh/sshd_config"
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Port\\s"
    line: "Port {{ zoidy_troglodyte_ssh_port }}"
    state: present
  notify: Restart sshd
  when: zoidy_troglodyte_ssh_port != 22

- name: Disallow X11 traffic forwarding
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^X11Forwarding"
    line: "X11Forwarding no"
    state: present
  notify: Restart sshd

- name: Enable DNS hostname checking (verify caller IP)
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^UseDNS"
    line: "UseDNS yes"
    state: present
  notify: Restart sshd

- name: Halve the number of connection attempts (to 3 from 6)
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^MaxAuthTries"
    line: "MaxAuthTries 3"
    state: present
  notify: Restart sshd

# ***

- name: Restrict SSH to specific user(s), perhaps
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AllowUsers"
    line: "AllowUsers {{ zoidy_troglodyte_ssh_restrict_user }}"
    state: present
  notify: Restart sshd
  when: zoidy_troglodyte_ssh_restrict_user != ''

# ***

# # This is purely to limit attack vectors.
# # (lb): But I cannot think how inet6 could be exploited.
# - name: Limit SSH to listening on IPv4
#   become: true
#   ansible.builtin.lineinfile:
#     dest: /etc/ssh/sshd_config
#     regexp: "^AddressFamily"
#     line: "AddressFamily inet"
#     state: present
#   notify: Restart sshd

# ***

# CXREF: https://github.com/DepoXy/sh-humble-prompt#🙇
#   ~/.kit/sh/sh-humble-prompt/lib/show-command-name-in-window-title.sh
#   ~/.kit/sh/sh-humble-prompt/lib/set-shell-prompt-and-window-title.sh
# - This setting a tad out of place, or at least the file title of
#   this task suggests we're "hardening" the config, but this doesn't
#   do that. We're just piggy-backing on the one Zoidy Pooh Ansible
#   task that edits sshd_config, so we can help out Homefries.
- name: AcceptEnv ITERM_SESSION_ID so Homefries can number terminal window titles
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    # REFER/2025-09-12: Debian 13 adds these 2 lines (not found in Linux Mint):
    #   # Allow client to pass locale and color environment variables
    #   AcceptEnv LANG LC_* COLORTERM NO_COLOR
    # SPIKE/DUNNO: Does config file support more than one ^AcceptEnv line?
    # - HSTRY: Old approach creates second AccepEnv line:
    #     regexp: "^AcceptEnv ITERM_SESSION_ID"
    #     line: "AcceptEnv ITERM_SESSION_ID"
    #   - Nowadays we replace existing AcceptEnv line.
    regexp: "^AcceptEnv "
    line: "AcceptEnv LANG LC_* COLORTERM NO_COLOR ITERM_SESSION_ID"
    state: present
  notify: Restart sshd

# ***
