# vim:tw=0:ts=2:sw=2:et:norl:ft=yaml.ansible
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/landonb/zoidy_troglodyte#🧔
# License: GPLv3
---

# REFER:
#
#   systemctl list-timers
#
# E.g,
#
#   $ systemctl list-timers
#
#   ... # An approximation of the output:
#   2024-03-21 16:46 11h left  2024-03-15 00:53 6d ago     update-notifier-motd.timer
#   2024-03-22 00:04 18h left  2024-03-21 00:36 4h55m ago  mintupdate-automation-upgrade.timer
#   2024-03-22 05:08 23h left  2024-03-21 05:08 22m ago    update-notifier-download.timer
#   2024-03-25 00:22  3d left  2024-03-20 08:42 20h ago    mintupdate-automation-autoremove.timer

# THOTS/2025-01-06: This unattended-upgrades task is now opt-in.
# - E.g.,
#     ansible-playbook path/to/site.yml -l hostname --tags unattended-installs -K
# - Author had u-u enabled for years on Linux Mint without issue, but:
#   - There's always a possibility that an upgrade will break your
#     workstation and impede your work for the day.
#   - Also, I had never wired a reboot mechanism, so I rarely rebooted
#     to realize kernel upgrades.
#     - More recently, I've updated the shell to warn-tell when
#       /var/run/reboot-required file detected. You'll find it
#       in the DepoXy shell scripts:
#         remind_restart_required
#           https://github.com/DepoXy/depoxy#🍯
#             https://github.com/DepoXy/depoxy/blob/release/core/mindencfs.sh
#     - It might also be nice to email when upgrades are applied,
#       as a heads-up, and to include a summary of changes. But
#       we're not that fancy.
#   - Finally, if the target host is a workstation, it's likely behind
#     a firewall that shoud mitigate most attacks (esp. if you only
#     have SSH exposed).
#     - As in, you're probably not at much risk if you don't always
#       upgrade immediately.
#     - On the other hand, if the target is a server, you have to decide
#       if having a patched system that's never more than 1 day behind
#       bugfixes is worth risking downtime should an upgrade bork something.

# REFER/2026-03-17: Check if unattended-upgrades is installed, e.g.:
#
#     $ apt-cache policy unattended-upgrades
#     unattended-upgrades:
#       Installed: 2.12
#     ...
#
#     $ sudo dpkg-reconfigure -plow unattended-upgrades

# ***

# mintupdate aka unattended-installs aka unattended-upgrades

- name: Enable automatic Mint updates
  become: true
  when: ansible_facts['distribution'] == 'Linux Mint'
  ansible.builtin.shell: mintupdate-automation upgrade enable

# ALTLY/2024-03-21: Instead of the timer (or in addition to it,
# hey why not, it won't hurt, but nor will it help), you could
# use the included `mintupdate` cron job.
# - This is included (and not simply deleted) mostly for
#   illustrative purposes.

# Place the same cron job that Update Manager places when you go to its
# Preferences > Auto-upgrade [tab] > ✓ Apply updates automatically.
- name: Install Auto-upgrades cron.daily job
  become: true
  when: ansible_facts['distribution'] == 'Linux Mint'
  ansible.builtin.copy:
    src: mintupdate
    dest: /etc/cron.daily/mintupdate
    mode: '0775'
  # ISOFF/2024-03-21: See note above. This is alt to timer.
  when: false

# ***

# REFER:
# https://wiki.debian.org/UnattendedUpgrades              <-- Useful
#   https://packages.debian.org/source/bookworm/unattended-upgrades
#     https://packages.debian.org/bookworm/unattended-upgrades
#       https://github.com/mvo5/unattended-upgrades       <-- Useful
#   https://packages.debian.org/bookworm/apt-listchanges
#     https://packages.debian.org/source/bookworm/apt-listchanges
#       https://salsa.debian.org/debian/apt-listchanges
#
# REFER:
#   # Check if enabled: You'll see "1"s, not "0"s:
#   cat /etc/apt/apt.conf.d/20auto-upgrades
#   # Enable or Disable unattended-upgrades via Yes/No prompt:
#   sudo dpkg-reconfigure unattended-upgrades
#
# SAVVY: Before unattended-upgrades runs, on Debian, you may see
# a GNOME Software toast (notification) that indicates that
# updates are available, and that they require a reboot.
# - But then after upgrading, you won't necessarily have to
#   reboot (and /var/run/reboot-required won't exist).
# - It basically seems like the OS doesn't know if you'll need
#   to reboot or not, and hedges its bets, and tells you you will.

- name: Install unattended-upgrades and apt-listchanges packages
  become: true
  when: ansible_facts['distribution'] == 'Debian'
  ansible.builtin.apt: name={{ item }}
  loop:
    - unattended-upgrades
    - apt-listchanges

# INERT/2025-01-05: We'll leave 'unattended-upgrades' disabled for now.
# - I'm not sure we should enable it.
# - HSTRY: I've just it for years on Linux Mint, although I *rarely*
#   rebooted, so at least kernel updates didn't get applied often,
#   even though they'd be installed.
#   - The main risk is workstation disruption, i.e., if an update
#     fails, or if a newer software version fails, what you wanted
#     to work might be disrupted.
#   - Author has only ever had one issue, and it was in `tree` of
#     all things (which is used by Password Store `pass` command).
#     - I also found the issue because macOS Homebrew automatic
#       updates, so not an aptitude-related issue, but related to
#       automatic software updating in general.
#     - And though it interrupted my work for a bit, it also encouraged
#       me to submit a PR to `tree`, and now my name in the changelog!
#       - So there's the risk that an automatic update disrupts your
#         work — but there's also a possible reward (if you see it
#         this way) that you could submit a patch so some widely-used
#         utility, too.
# - INERT: In any case, we'll install the 2 libraries you'd need, one
#   to run unattended-upgrades, and another you could use to email a
#   list of changes applied by an upgrade.
#   - MAYBE: In the least, I'm curious about automating an email to
#     let me know when it's time to upgrade packages. Because lately
#     I only logon my Linux hosts over SSH, and my SSH logon message
#     doesn't tell me when there are updates available.
