---

# ***

# Place the same cron job that Update Manager places when you go to its
# Preferences > Auto-upgrade [tab] > ✓ Apply updates automatically.
- name: Install Auto-upgrades cron.daily job
  become: yes
  copy:
    src: mintupdate
    dest: /etc/cron.daily/mintupdate
    mode: 0775

