---

- name: Persist iptables
  become: yes
  # Note: This creates /etc/iptables/rules.v4|v6
  command: service netfilter-persistent save
  # 2023-04-14: An older shell (pre ansible.builtin.shell?) warned to
  # tell us that 'save' is not a valid (Ansible) service module state.
  # But latest Ansible does not have 'warn' option (nor does it warn
  # against 'save' state anymore, as far as I've seen).
  #   args:
  #     warn: False

# ***

# BWARE/2025-01-05: Keep SSH Restart at the bottom of this file, so it runs *last*
#
# - DUNNO/2025-01-05: I've seen in past that `Persist iptables` fails if
#   run after restarting SSH (if SSH port number was changed).
#   - But for some reason, I don't see that happening today (on Debian 12;
#     albeit last time I saw the issue was on Linut Mint 21.3).
#
# - SAVVY: In any case, call SSH restart last in case port number changes.
#   - Otherwise, some other call might fail because original ansible-playbook
#     call specifies a port number that's since been changed.
#   - And if you `-vvv` the play, you'll this is the last SSH call that's made.

# I.e., sudo systemctl restart ssh
- name: Restart sshd
  become: yes
  service: name=sshd state=restarted

