# vim:tw=0:ts=2:sw=2:et:norl:ft=yaml.ansible
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/landonb/zoidy_troglodyte#🧔
# License: GPLv3
---

  # SAVVY: This creates /etc/iptables/rules.v4|v6
  # - HSTRY/2025-11-11: Previous a command:
  #     ansible.builtin.command: service netfilter-persistent save
  #   But then Ansible Lint complains:
  #     "service used in place of service module"
  #   Though I'm not sure how to use service module to "save";
  #   but I did find iptables_state module (and fortunately
  #   we can use a with_items loop to update both ipv4 and
  #   ipv6, because I don't think you can wire more than
  #   one 'notify' handler).
- name: Persist iptables
  become: true
  community.general.iptables_state:
    ip_version: "ip{{ item }}"
    table: filter
    state: saved
    path: "/etc/iptables/rules.{{ item }}"
  with_items:
    - v4
    - v6

# ***

# BWARE/2025-01-05: Keep SSH Restart at the bottom of this file, so it runs *last*
#
# - DUNNO/2025-01-05: I've seen in past that `Persist iptables` fails if
#   run after restarting SSH (if SSH port number was changed).
#   - But for some reason, I don't see that happening today (on Debian 12;
#     albeit last time I saw the issue was on Linut Mint 21.3).
#
# - SAVVY: In any case, call SSH restart last in case port number changes.
#   - Otherwise, some other call might fail because original ansible-playbook
#     call specifies a port number that's since been changed.
#   - And if you `-vvv` the play, you'll this is the last SSH call that's made.

# I.e., sudo systemctl restart ssh
- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

# ***
